name: Sync with upstream
on:
  push:
  schedule:
    - cron: "3 */8 * * *"
  workflow_dispatch:

jobs:
  sync-mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update mirror
        uses: fshp/golang-dist-mirror-action@workdir
        with:
          workdir: backend
          token: ${{ secrets.PUSH_TOKEN }}
